vim.keymap.set('i', 'jj', '<Esc>')
vim.keymap.set('i', 'っｊ', '<Esc>')
vim.keymap.set('n', 'sj', '<C-w>j')
vim.keymap.set('n', 'sk', '<C-w>k')
vim.keymap.set('n', 'sh', '<C-w>h')
vim.keymap.set('n', 'sl', '<C-w>l')
vim.keymap.set('v', '<', '<gv')
vim.keymap.set('v', '>', '>gv')
vim.keymap.set('n', 'p', ']p')
vim.keymap.set('n', 'P', ']P')
vim.keymap.set('n', 'Y', 'y$')
vim.keymap.set('n', '+', '<C-a>')
vim.keymap.set('n', '-', '<C-x>')
vim.keymap.set('n', '<Esc><Esc>', ':set hlsearch<CR>')
vim.keymap.set('n', '<C-t>', '<Cmd>belowright new<CR><Cmd>terminal<CR><Cmd>resize 20<CR><Cmd>startinsert!<CR>')
vim.keymap.set('t', '<C-t>', '<Cmd>close<CR>')
vim.keymap.set('t', 'jj', '<C-\\><C-n>')
vim.keymap.set('t', 'sj', '<C-w>j')
vim.keymap.set('t', 'sk', '<C-w>k')
vim.keymap.set('t', 'sh', '<C-w>h')
vim.keymap.set('t', 'sl', '<C-w>l')
