local k = vim.keymap.set
k('i', 'jj', '<Esc>')
k('i', 'っｊ', '<Esc>')
k('n', 'sj', '<C-w>j')
k('n', 'sk', '<C-w>k')
k('n', 'sh', '<C-w>h')
k('n', 'sl', '<C-w>l')
k('n', '<C-n>', '<Cmd>new<CR>')
k('v', '<', '<gv')
k('v', '>', '>gv')
k('n', 'p', ']p')
k('n', 'P', ']P')
k('n', 'Y', 'y$')
k('n', '+', '<C-a>')
k('n', '-', '<C-x>')
k('n', '<Esc><Esc>', ':set hlsearch<CR>')
k('n', '<C-t>', '<Cmd>belowright new<CR><Cmd>terminal<CR><Cmd>resize 15<CR><Cmd>startinsert!<CR>')
k('n', 'gk', '<Cmd>lua vim.lsp.buf.hover()<CR>')
k('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>')
k('n', 'gf', '<Cmd>lua vim.lsp.buf.formatting()<CR>')
k('n', 'gr', '<Cmd>lua vim.lsp.buf.references()<CR>')
k('n', 'gc', '<Cmd>lua vim.lsp.buf.rename()<CR>')
k('n', 'ga', '<Cmd>lua vim.lsp.buf.code_action()<CR>')
k('t', '<C-t>', '<Cmd>close<CR>')
k('t', 'jj', '<C-\\><C-n>')
k('t', 'sj', '<C-w>j')
k('t', 'sk', '<C-w>k')
k('t', 'sh', '<C-w>h')
k('t', 'sl', '<C-w>l')
