vim.cmd('let g:loaded_gzip              = 1')
vim.cmd('let g:loaded_tar               = 1')
vim.cmd('let g:loaded_tarPlugin         = 1')
vim.cmd('let g:loaded_zip               = 1')
vim.cmd('let g:loaded_zipPlugin         = 1')
vim.cmd('let g:loaded_rrhelper          = 1')
vim.cmd('let g:loaded_2html_plugin      = 1')
vim.cmd('let g:loaded_vimball           = 1')
vim.cmd('let g:loaded_vimballPlugin     = 1')
vim.cmd('let g:loaded_getscript         = 1')
vim.cmd('let g:loaded_getscriptPlugin   = 1')
vim.cmd('let g:loaded_netrw             = 1')
vim.cmd('let g:loaded_netrwPlugin       = 1')
vim.cmd('let g:loaded_netrwSettings     = 1')
vim.cmd('let g:loaded_netrwFileHandlers = 1')

require("init/Plugin")
